### ISSUE TITLE
API是否不支持联网搜索

### ISSUE THREAD

**Issue by a927445851** [MoonshotAI/MoonshotAI-Cookbook#15]
## 背景:
给出某个条件,要求在互联网中找到合适的答案
## 模型:
128k&kimi.moonshot.cn/chat
## 条件:
完全一致
## 结果:
- api:大多是无法找到相关信息
- 线上:能输出理想的答案
## 问题:
现在是否api有限制无法联网,或是模型的原因

**Comment by WendaoLee** [comment]
根据[官方文档](https://platform.moonshot.cn/docs/intro#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，搜索功能是没有开放对应api的：
> 是否开放类似 Kimi 智能助手中的搜索接口？
>   目前并没有开放搜索的计划，API 用户可以使用例如 [Apify](https://apify.com/)、[Crawlbase](https://zh-cn.crawlbase.com/enterprise) 或者 [ArchiveBox](https://github.com/ArchiveBox/ArchiveBox) 等第三方解决方案。
