### ISSUE TITLE
The engine is currently overloaded, please try again later

### ISSUE THREAD

**Issue by zhoudf10** [MoonshotAI/MoonshotAI-Cookbook#16]
请问我在用：java调用文件回答问题时，用8K，32K模型，[The engine is currently overloaded, please try again later](error: {"error":{"message":"The engine is currently overloaded, please try again later","type":"engine_overloaded_error"}})
文件信息：TokenCount(code=0, data=TokenCount.Data(totalTokens=2773), scode=0x0, status=true) @lychees

**Comment by lychees** [comment]
当前计算资源有些紧张，我们对用户使用了分级策略，具体请参考文档中 [充值与限速](https://platform.moonshot.cn/docs/pricing#%E5%85%85%E5%80%BC%E4%B8%8E%E9%99%90%E9%80%9F) 一节。

**Comment by zhoudf10** [comment]
我看了一下，4个指标我都没有超过，还是一样的错误，我是Free用户。
并发：一个单线程1个请求
RPM：刚刚重新请求了一次
TPM：totalTokens=2773
TPD：5000
@lychees

**Comment by zhoudf10** [comment]
我上传的文件是个12K的txt文件，问题也是测试总结内容。
方法：将文件内容读取和问题放在一个chat中发送。

**Comment by lychees** [comment]
free 用户在计算资源紧张的高峰期会被限制。

**Comment by zhoudf10** [comment]
@lychees 还有个问题，就是API接口调用对话，每次都是一个新的会话还是一直都是延用1个会话，然后通过key去分辨会话。谢谢
