### ISSUE TITLE
成功了 几次  然后就一直报这个错。 我的messsage 明显不是空的！！！

### ISSUE THREAD

**Issue by dagedan** [MoonshotAI/MoonshotAI-Cookbook#34]
{"error":{"message":"Invalid request: agent message content is empty","type":"invalid_request_error"}}

**Comment by yuikns** [comment]
请给出请求的裸 json 我这儿也试试？

**Comment by dagedan** [comment]
@yuikns 
`[{"role":"system","content":"你是一个专业的编剧，你更擅长重写简短的剧情文案。并善于润色文案"},{"role":"user","content":"卢俊义喝了御酒，水银进入体内，突然感觉腰肾非常痛，坐卧不安，下人本想请郎中，卢俊义怕耽误行程，还决定第二天坐船离京。"},{"role":"user","content":"第二天，卢俊义要喝酒暖身，怎奈毒气已在体内，他拿着酒杯到船头时，一个趔趄就摔到了水里，救援不及。可怜河北玉麒麟，屈作水中冤抑鬼。"},{"role":"user","content":"蔡京等人主张给宋江赐酒，宿太尉说圣上，宋江乃忠义之人，不能赐毒酒给他呀，皇帝大惊，连忙请追回毒酒。"},{"role":"user","content":"宋江枯坐在一旁，手里拨着桌上的乱棋，感叹着，输了，输了，既然输了，皇上赐的这杯御酒，就该我喝。"},{"role":"user","content":"李逵来了，本想跟宋江解闷，宋江在说着遗言时，回头猛地一看，李逵却把那壶毒酒喝了个精光，宋江满含热泪，李逵说，俺铁牛生的时候跟着哥哥，既然哥哥执意要走，那俺铁牛也跟着，说着就跪倒在宋江怀里。宋江哭着喊着兄弟，两人都痛着。之后李逵就说这外面的天地怎么都红了，宋江说是日头落了。之后李逵就闭眼了。宋江歪坐在门外椅子上，之后扑通倒地。"},{"role":"user","content":"吴用来到宋江和李逵的墓前，说招安之前，我和公孙胜曾经发誓，当时公孙胜说，招安之后，公明哥哥必遭杀害，自古兔死狗烹，公明哥哥是首恶，欲加之罪何患无辞，吴用说，我一定要助哥哥招安，如果哥哥去了，就追随他去，九死不悔。"},{"role":"user","content":"花荣也来到了墓前，说朝廷既已生疑，必然陷我等莫须有罪过，不如今日小弟与吴用共赴黄泉。说罢两人双双自缢于墓旁大树。"},{"role":"user","content":"朱武来找公孙胜出家，终养天年，李俊等人投化外国，童威等人去外国做了高官，戴宗出家，一日大笑而终，阮小七回家养老母，杜兴和李应还乡，一起做了富豪。柴进回老家，无疾而终，穆春回家为良民，孙立和顾大嫂等依然登州任用。安道全在太医院，皇甫端在御马监，乐和在驸马府中，金大坚在御宝监，萧让在太师府，凌振在火药局，黄信仍任青州，呼延灼破大金兀四太子，后阵亡。关胜在大名府，后来醉酒落马得病而亡。"},{"role":"user","content":"皇帝来到人去楼空的李师师房内，宿太尉跟皇帝说起宋江被害，皇帝说寡人知道是何人所为，惩处奸佞不在此一时。"},{"role":"user","content":"皇帝传旨，让宋清承袭宋江名爵，敕封宋江为侯，让人在梁山泊盖起庙宇，祭奠宋江，皇上还要亲笔题字。那里的庙宇，至今香火依然旺盛。"},{"role":"user","content":"把以上这些剧情文案重写成幽默的,单条100个字左右,并输出json"},{"role":"assistant","name":"","content":"","partial":true}]`

**Comment by dagedan** [comment]
我是n条文案，想转写一下。 大佬指点一下  这样做对不对？ @yuikns

**Comment by yuikns** [comment]
@dagedan 不敢称，共同学习。

这儿主要是最后一个 partial 检查失败了。有个约定就是每个 message 都要有内容。

```
{"role":"assistant","name":"","content":"","partial":true}
```

最后一个 message 这儿如果要过输入检查，希望至少 name 非空或者 content 至少有一个字符。

我理解这儿是希望先简单实现类似 json mode 的效果。那么这个 trick 是基于"把话塞嘴里"这种场景。

那么这儿应该改成这样：

```
{"role":"assistant","name":"","content":"{","partial":true}
```

也就是说，要求模型假定自己已经输出了一个 "{" 然后继续输出。（注意，这时候模型不会再输出 `{` 了。

模型的输出结果可能是

`"foo": "bar" }`

再拼上您最开始的塞到它嘴里的 `{` 就是完整的 json 了。

python 的等价表示：

```python
def example_call():
    response = client.chat.completions.create(
        model=model_id,
        messages=[
            {
                "role": "system",
                "content": "你是一个专业的编剧，你更擅长重写简短的剧情文案。并善于润色文案",
            },
            {
                "role": "user",
                "content": "卢俊义喝了御酒，水银进入体内，突然感觉腰肾非常痛，坐卧不安，下人本想请郎中，卢俊义怕耽误行程，还决定第二天坐船离京。",
            },
            {
                "role": "user",
                "content": "第二天，卢俊义要喝酒暖身，怎奈毒气已在体内，他拿着酒杯到船头时，一个趔趄就摔到了水里，救援不及。可怜河北玉麒麟，屈作水中冤抑鬼。",
            },
            {
                "role": "user",
                "content": "蔡京等人主张给宋江赐酒，宿太尉说圣上，宋江乃忠义之人，不能赐毒酒给他呀，皇帝大惊，连忙请追回毒酒。",
            },
            {
                "role": "user",
                "content": "宋江枯坐在一旁，手里拨着桌上的乱棋，感叹着，输了，输了，既然输了，皇上赐的这杯御酒，就该我喝。",
            },
            {
                "role": "user",
                "content": "李逵来了，本想跟宋江解闷，宋江在说着遗言时，回头猛地一看，李逵却把那壶毒酒喝了个精光，宋江满含热泪，李逵说，俺铁牛生的时候跟着哥哥，既然哥哥执意要走，那俺铁牛也跟着，说着就跪倒在宋江怀里。宋江哭着喊着兄弟，两人都痛着。之后李逵就说这外面的天地怎么都红了，宋江说是日头落了。之后李逵就闭眼了。宋江歪坐在门外椅子上，之后扑通倒地。",
            },
            {
                "role": "user",
                "content": "吴用来到宋江和李逵的墓前，说招安之前，我和公孙胜曾经发誓，当时公孙胜说，招安之后，公明哥哥必遭杀害，自古兔死狗烹，公明哥哥是首恶，欲加之罪何患无辞，吴用说，我一定要助哥哥招安，如果哥哥去了，就追随他去，九死不悔。",
            },
            {
                "role": "user",
                "content": "花荣也来到了墓前，说朝廷既已生疑，必然陷我等莫须有罪过，不如今日小弟与吴用共赴黄泉。说罢两人双双自缢于墓旁大树。",
            },
            {
                "role": "user",
                "content": "朱武来找公孙胜出家，终养天年，李俊等人投化外国，童威等人去外国做了高官，戴宗出家，一日大笑而终，阮小七回家养老母，杜兴和李应还乡，一起做了富豪。柴进回老家，无疾而终，穆春回家为良民，孙立和顾大嫂等依然登州任用。安道全在太医院，皇甫端在御马监，乐和在驸马府中，金大坚在御宝监，萧让在太师府，凌振在火药局，黄信仍任青州，呼延灼破大金兀四太子，后阵亡。关胜在大名府，后来醉酒落马得病而亡。",
            },
            {
                "role": "user",
                "content": "皇帝来到人去楼空的李师师房内，宿太尉跟皇帝说起宋江被害，皇帝说寡人知道是何人所为，惩处奸佞不在此一时。",
            },
            {
                "role": "user",
                "content": "皇帝传旨，让宋清承袭宋江名爵，敕封宋江为侯，让人在梁山泊盖起庙宇，祭奠宋江，皇上还要亲笔题字。那里的庙宇，至今香火依然旺盛。",
            },
            {
                "role": "user",
                "content": "把以上这些剧情文案重写成幽默的,单条100个字左右,并输出json",
            },
            {"role": "assistant", "name": "", "content": "{", "partial": True}, # content 非空
        ],
        temperature=0.3,
    )
    result = response.choices[0].message.content
    print("结果是：")
    print("{" + result) # 注意此处加了个 "{"
```

sample output:

`{"plot1": "卢俊义误饮御酒，水银入肚，腰肾痛得像被踢了一脚。他本想忍忍，结果第二天上船，一个趔趄，直接跳水里，成了‘水中芭蕾’的领舞。", "plot2": "宋江想喝酒暖身，却不知毒酒已在体内‘暖’过头。船头一趔趄，直接跳水，演绎了一出‘跳水冠军’的戏码。", "plot3": "蔡京想给宋江下毒，宿太尉急忙阻止：‘皇上，宋江可是忠义的代表，毒酒可不行！’皇帝一惊，连忙追回毒酒，宋江却已自饮，真是‘忠义’过头。", "plot4": "宋江拨乱棋，感叹‘输了’，皇上赐的酒，他决定喝。李逵却抢先一步，把毒酒喝光，两人抱头痛哭，李逵说：‘哥哥，我陪你一起走。’宋江泪目：‘好兄弟，咱们一起‘跳河’。", "plot5": "吴用在墓前发誓，要助宋江招安，如果宋江去了，就追随他。花荣也来，两人决定共赴黄泉，真是‘黄泉路上不孤单’。", "plot6": "朱武找公孙胜出家，李俊等人投化外国，童威等人成了高官，戴宗出家，大笑而终，阮小七回家养老母，杜兴和李应成了富豪。柴进回老家，无疾而终，穆春回家为良民，孙立和顾大嫂等依然登州任用。安道全在太医院，皇甫端在御马监，乐和在驸马府中，金大坚在御宝监，萧让在太师府，凌振在火药局，黄信仍任青州，呼延灼破大金兀四太子，后阵亡。关胜在大名府，后来醉酒落马得病而亡。", "plot7": "皇帝来到李师师房内，宿太尉说起宋江被害，皇帝说：‘寡人知道是何人所为，惩处奸佞不在此一时。’看来皇帝也是‘事后诸葛亮’。", "plot8": "皇帝传旨，让宋清承袭宋江名爵，敕封宋江为侯，让人在梁山泊盖起庙宇，祭奠宋江，皇上还要亲笔题字。那里的庙宇，至今香火依然旺盛，宋江成了‘香火旺盛’的代言人。"}`

不知是否符合需求。


关于 partial，也可以这样处理，也可以不判为空：

```
[
  {
    "role": "system",
    "content": "你是一个戏精"
  },
  {
    "role": "user",
    "name": "李逵",
    "content": "我说哥哥！我们杀去东京，夺了鸟位！我们都做将军，在那里快活，却不好？"
  },
  {
    "role": "assistant",
    "name": "宋江",
    "partial": true
  }
]
```

这样由于有 name 也是符合期待的。但是至少要有个地方有内容。

关于 json mode, 我们即将 release，敬请期待。
