### ISSUE TITLE
何时集成langchain

### ISSUE THREAD

**Issue by 1137882300** [MoonshotAI/MoonshotAI-Cookbook#5]
请问什么时候可以集成 langchain 呀？

**Comment by lychees** [comment]
现在就可以

```
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    openai_api_base="https://api.moonshot.cn/v1/", 
    openai_api_key="...",
    model_name="moonshot-v1-8k",
    temperature=0.7,
)
print(llm.invoke("how can langsmith help with testing?"))
```

**Comment by 1137882300** [comment]
> 现在就可以
> 
> ```
> from langchain_openai import ChatOpenAI
> 
> llm = ChatOpenAI(
>     openai_api_base="https://api.moonshot.cn/v1/", 
>     openai_api_key="...",
>     model_name="moonshot-v1-8k",
>     temperature=0.7,
> )
> print(llm.invoke("how can langsmith help with testing?"))
> ```

为什么报错：找不到？ 请问哪个版本 是支持的？ AttributeError: module 'openai' has no attribute 'OpenAI'

**Comment by 1137882300** [comment]
> 现在就可以
> 
> ```
> from langchain_openai import ChatOpenAI
> 
> llm = ChatOpenAI(
>     openai_api_base="https://api.moonshot.cn/v1/", 
>     openai_api_key="...",
>     model_name="moonshot-v1-8k",
>     temperature=0.7,
> )
> print(llm.invoke("how can langsmith help with testing?"))
> ```

thank you very much， OK
