### ISSUE TITLE
有一点点疑问

### ISSUE THREAD

**Issue by dingding668** [MoonshotAI/MoonshotAI-Cookbook#6]
工具类是一种调用api的方式，然后helloword也是一种调用api的方式，两种方式都可以是嘛？

**Comment by lychees** [comment]
请问具体是指什么调用方式？

**Comment by dingding668** [comment]
其实是我菜，那个hello里面相当于是先封装了一个client然后再进行调用我这样理解对吗?还有就是hello里面好像缺少了关于文件处理的部分

**Comment by lychees** [comment]
那个hello里面相当于是先封装了一个client然后再进行调用我这样理解对吗?
是的。
