### ISSUE TITLE
Java sdk里测试失败缺少代码

### ISSUE THREAD

**Issue by cabudon** [MoonshotAI/MoonshotAI-Cookbook#7]
ApiTest里的chat会报错error: invalid request: messages must not be empty

需要加上这两处
![image](https://github.com/MoonshotAI/MoonshotAI-Cookbook/assets/53213231/e243df56-112a-432b-a802-e1546a5c8ee3)
![image](https://github.com/MoonshotAI/MoonshotAI-Cookbook/assets/53213231/abf1f20e-c438-4e49-bd71-4733b782124b)

**Comment by lychees** [comment]
感谢，收到！

**Comment by dakai6677** [comment]
这个代码里 就没有地方能报出来 
messages must not be empty 
我很好奇你咋测的
